### ISSUE TITLE
Can't unselect letters previously selected

### ISSUE THREAD

**Issue by nicholaschiang** [nicholaschiang/hammock#25]
Currently, users can unselect letters that they have previously selected (because of a sync with their user object that isn't properly updated when a letter is unselected I think):

https://user-images.githubusercontent.com/20798889/117173848-04a1d300-ad82-11eb-8634-9d0b3722196b.mov

Related to #15 (a similar issue about unselecting letters).

**Comment by nicholaschiang** [comment]
Fixed by 6b4b9dd.

**Comment by nicholaschiang** [comment]
It seems like relying on the global `mutate` function for state management isn't very consistent, as users will sometimes be prevented from interacting at all with the subscriptions list:

https://user-images.githubusercontent.com/20798889/117684363-c6cdf180-b169-11eb-8f50-5aaf498cc4a0.mov

**Comment by nicholaschiang** [comment]
Clicking outside of the tab and then refocusing the tab seems to get rid of the problem... something to do with SWR OFC.

**Comment by jurajpal** [comment]
@nicholaschiang even once I was able to select a few of them and then clicked away to a different window to do something else and then came back, they were unchecked again.

**Comment by nicholaschiang** [comment]
@jurajpal see #27 (that's the issue you're encountering).
