### ISSUE TITLE
Use plain text to estimate reading times

### ISSUE THREAD

**Issue by martinsrna** [nicholaschiang/hammock#32]
Convert the HTML emails into plain text before sending it over to that [`reading-time`](https://npmjs.com/package/reading-time) package. Currently, the time estimates are way off because of this (for some reason, `reading-time` seems to include HTML markup in its estimates).

**Comment by nicholaschiang** [comment]
@martinsrna I've decided just to try using another package. Parsing HTML really shouldn't be something that I have to do here. I figured that there was probably a fancier solution that could also e.g. account for images and there was:
- https://github.com/pritishvaidya/read-time-estimate/
- https://www.freecodecamp.org/news/how-to-more-accurately-estimate-read-time-for-medium-articles-in-javascript-fb563ff0282a/
