### ISSUE TITLE
Add Segment analytics and sync with Mixpanel/GA/FullStory

### ISSUE THREAD

**Issue by nicholaschiang** [nicholaschiang/hammock#4]
- [x] Instead of including `ga.js`, we will only load a single analytics script from Segment (their `a.js` v2 beta).
- [ ] Start tracking identify and events that @jurajpal and @martinsrna want (talk to them first about what's important).
- [x] Setup a new Segment workspace and give @jurajpal and @martinsrna access so they can sync the data with their favorite tools (e.g. GA, Mixpanel, Fullstory, Intercom).
- [ ] Ensure that adding the script doesn't decrease Lighthouse performance scores.

ETA - 60mins

**Comment by jurajpal** [comment]
@nicholaschiang just an FYI, we have GA set up for the Webflow website so once we have the Segment workspace, I'll be able to connect them two.

**Comment by martinsrna** [comment]
Fyi, I created and added you to Segment workspace

**Comment by nicholaschiang** [comment]
@martinsrna I'm going to create and use my own workspace (I think it's best if I do these things) because I want to use an ID that is consistent with our GCP project IDs. That way, I only need one environment variable to specify both the GCP project IDs and Segment workspace IDs. I'll add you to it once I'm done.

**Comment by nicholaschiang** [comment]
@jurajpal @martinsrna Feel free to help fill [this spreadsheet](https://docs.google.com/spreadsheets/d/1j4f3oYp6elLt6BfwS4reb9VCzdBCfryrFsFJ0Q3_90c/edit#gid=0) out with any other events you want to track. I'm using Segment's [suggested "Object-Action" event naming framework](https://segment.com/academy/collecting-data/naming-conventions-for-clean-data/) which is why there's two columns (one for the object, one for the action).
