### ISSUE TITLE
Feed doesn't load new newsletters

### ISSUE THREAD

**Issue by martinsrna** [nicholaschiang/hammock#41]
I have new messages with the Hammock label in Gmail, but they don't show up in the feed.

Is there any push / pull mechanism we can use here so the feed is always up to date?

After logging out & logging in, they are there.

![image](https://user-images.githubusercontent.com/80906500/118611499-e75e0300-b78a-11eb-9625-79620b7663ed.png)

**Comment by nicholaschiang** [comment]
Closing as a duplicate of #38.

**Comment by martinsrna** [comment]
Ah sorry! Forgot it's the same thing as yesterday.
