### ISSUE TITLE
Archive newsletters that have already been read

### ISSUE THREAD

**Issue by nicholaschiang** [nicholaschiang/hammock#5]
From @jurajpal (or @martinsrna, I'm not sure) [on Notion](https://www.notion.so/2020hibiki/3d3efdb2ee0e43cf8bbfd1c0351d97c3?v=852f2ff9f02c422f90c445b33cd8953a&p=a0a1777b0d394d258cb8f8f31a963a3c):

Regarding the archive feature - thinking there could be 2 ways:
- Manual - add a button next to the ‘x’ and arrows ‘✅ Archive’
- Automatic - if user scrolls through e.g. 30%, it automatically goes to Achive

The Feed then only displays newsletters that are still unread in Gmail inbox and all the read ones and those marked as Archive are in Archive “feed” accessible from user profile menu.
- Tracking where you are in the email, archive based on the scroll position?

**Comment by martinsrna** [comment]
Quick question: We need to track scroll position - how does this impact permissions / what we need to store on our end?

Also:
- Manual - add a button next to the ‘x’ and arrows ‘✅ Archive’ (Update [Figma](https://www.figma.com/file/968zBs03dtG5hS2pJOagcv/Newsletter-Reader-prototype?node-id=0%3A1))
Automatic - if user scrolls through e.g. **100%**, it automatically goes to Achive (this should be subject to A/B test and User Research later)

**Comment by nicholaschiang** [comment]
@martinsrna Tracking scroll position would be pretty easy and wouldn't require any additional permissions. Essentially, I'd just add a database record for each email (using the `messageId` provided by Gmail's API) and then save metadata about that email in its record (e.g. scroll position, who it's from, etc).

**Comment by martinsrna** [comment]
That's great news, let's do it this way for sure.
